# Site settings
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Br3nt's Place

email: your-email@example.com

description: >-
  Welcome to my digital expression! I hope you have some while you're here :)

author_alias: &alias br3nt
author: &author Brent Jacobs

collections:
  code_pens:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      # author: *author
      # author_alias: *alias
  - scope:
      path: ""
      type: code_pens
    values:
      layout: code_pen
      # author: *author
      # author_alias: *alias
  - scope:
      path: ""
    values:
      layout: default
      author: *author
      author_alias: *alias

plugins:
  - github-pages
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
