# Site settings
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Br3nt's Place

email: your-email@example.com

description: >-
  Welcome to my digital expression! I hope you have some while you're here :)

author_alias: &alias br3nt
author: &author Brent Jacobs

collections:
  code_pens:
    output: true
  games:
    output: true
  reviews:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: code_pens
    values:
      layout: code_pen
  - scope:
      path: ""
    values:
      layout: default
      author: *author
      author_alias: *alias
  - scope:
      path: ""
      type: games
    values:
      layout: game
  - scope:
      path: ""
      type: reviews
    values:
      layout: default

plugins:
  - github-pages
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
