# see: https://jekyllrb.com/docs/continuous-integration/github-actions/

name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
      - main # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      # from https://medium.com/@mehdi.h/using-jekyll-with-tailwindcss-on-github-pages-50c3d8401230
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
         build_dir: _site/
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
