# see: https://jekyllrb.com/docs/continuous-integration/github-actions/

name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
      - main # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          jekyll_build_options: --trace
